### ISSUE TITLE
How to pass options?

### ISSUE THREAD

**Issue by corysimmons** [purifycss/gulp-purifycss#12]
Please add to README

**Comment by corysimmons** [comment]
Specifically I'd like to be able to log the rejected rules.

**Comment by iskrisis** [comment]
Have you figured it out? 
when i do 

.pipe(purify(['./index.html'],{ info: true, rejected: true})

info is loging but rejected option doesnt seem to log anything (even though i know its removing stuff because i compared the files myself)
