### ISSUE TITLE
Minify option is ignored

### ISSUE THREAD

**Issue by robin-ntriga** [purifycss/gulp-purifycss#21]
When passing along the option "minify: true" in my Gulpfile purifycss does NOT minify the result. If I manually change the default OPTIONS array in the purifycss.js file the minifaction does work. 
Passing along the option "output" in the same object seems to work too.

This might be related to the following issue with the Grunt package:
https://github.com/purifycss/grunt-purifycss/issues/7

**Comment by craftedsystems** [comment]
@robin-ntriga see https://github.com/purifycss/gulp-purifycss/pull/19
