### ISSUE TITLE
package doesn't exist in npm

### ISSUE THREAD

**Issue by niftylettuce** [purifycss/gulp-purifycss#5]
you haven't even published this yet?...

**Comment by jstejada** [comment]
:+1:

**Comment by gilly3** [comment]
Temporary work around until it is published, install from github:

```
npm i --save-dev purifycss/gulp-purifycss
```

**Comment by sotayamashita** [comment]
@gilly3 Please add the way on README.md

**Comment by edoecohen** [comment]
It was actually added by @corysimmons 
https://www.npmjs.com/package/gulp-purifycss

**Comment by kennyt** [comment]
`gulp-purifycss` thank you @corysimmons

**Comment by corysimmons** [comment]
:+1: This is officially maintained by @kennyt now. :tada:
